series:
  KENT: # category in config.yml
    - '나만 믿고 따라와 도시어부 시즌2'
    - '식스센스' 
    - '맛남의 광장' 
    - '어서와 한국은 처음이지 시즌2' 
    - '할명수' 
    - '라디오스타' 
    - '백종원의 골목식당' 
    - '침묵예능 아이콘택트' 
    - '찐한친구' 
    - '캐시백' 
    - '옥탑방의 문제아들' 
    - '연애의 참견 시즌3' 
    - '연애는 귀찮지만 외로운 건 싫어' 
    - '비디오 스타' 
    - '무엇이든 물어보살' 
    - '백파더' 
    - '동상이몽2 너는 내운명' 
    - '개는 훌륭하다' 
    - '신박한 정리' 
    - '프리한19' 
    - '서울촌놈' 
    - '1호가 될 순 없어' 
    - '구해줘 홈즈' 
    - '선을 넘는 녀석들 리턴즈' 
    - '미운 우리 새끼' 
    - '뭉쳐야 찬다' 
    - '코미디 빅리그' 
    - '집사부일체' 
    - '1박 2일 시즌4' 
    - '복면가왕' 
    - '집쿡라이브' 
    - '런닝맨' 
    - '전지적 참견 시점' 
    - 'TV 동물농장' 
    - '방구석 1열' 
    - '신비한TV 서프라이즈' 
    - '아는 형님' 
    - '놀라운 토요일' 
    - '장르만 코미디' 
    - '놀면 뭐하니' 
    - '신상출시 펀스토랑' 
    - '히든싱어 6' 
    - '맛있는 녀석들' 
    - '신서유기 8'
    - '쇼미더머니 9'
    - '세얼간이'
    - '나는 살아있다'
    - '유 퀴즈 온 더 블럭'
    - '대한외국인'
