folder:
### path of the folder/mountpoint for all the media, without the leading slash
  root: 500GB_SSD/AutoDownload/
### media and download paths, relative to the previous path
  kent: TV/
  kdrama: Drama/
  #kmusic: Music/
qbittorrent:
  host: qbittorrent
  port: 8088
  username: yourtorrentusername
  password: yourtorrentpass
